# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"hello": "Untitled.ipynb"}

modules = ["bone.py"]

doc_url = "https://d-genk.github.io/dog/"

git_url = "https://github.com/d-genk/dog/tree/master/"

def custom_doc_links(name): return None
